#!/usr/bin/env bash
#
# Install cskit into ~/.local/bin.
#
# The three standalone scripts (fixcode / exportcode / clonecode) are the
# rollback path: if cskit misbehaves you must still be able to run them. So this
# installer never silently overwrites them. Legacy shims are opt-in, and any
# existing regular file is backed up outside the repo first.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="${CSKIT_BIN_DIR:-$HOME/.local/bin}"
BACKUP_ROOT="${CSKIT_BACKUP_DIR:-$HOME/.cskit-backups}"
LEGACY_NAMES=(fixcode exportcode clonecode)

WITH_SHIMS=0
FORCE=0

usage() {
    cat <<'USAGE'
用法：./install.sh [选项]

选项：
  --with-shims   额外创建 fixcode / exportcode / clonecode 兼容命令
                 （已存在的同名文件会先备份到 ~/.cskit-backups）
  --force        覆盖已存在的 cskit 命令
  -h, --help     显示本帮助

环境变量：
  CSKIT_BIN_DIR      安装目录（默认 ~/.local/bin）
  CSKIT_BACKUP_DIR   备份目录（默认 ~/.cskit-backups）
USAGE
}

while [ $# -gt 0 ]; do
    case "$1" in
        --with-shims) WITH_SHIMS=1 ;;
        --force)      FORCE=1 ;;
        -h|--help)    usage; exit 0 ;;
        *) echo "✗ 未知选项：$1" >&2; usage >&2; exit 2 ;;
    esac
    shift
done

# --- sanity checks ---------------------------------------------------------

if [ ! -f "$REPO_DIR/cskit/__main__.py" ]; then
    echo "✗ 找不到 cskit 包：$REPO_DIR/cskit/__main__.py" >&2
    exit 1
fi

PYTHON="$(command -v python3 || true)"
if [ -z "$PYTHON" ]; then
    echo "✗ 找不到 python3" >&2
    exit 1
fi

PY_OK=$("$PYTHON" -c 'import sys; print(1 if sys.version_info >= (3, 9) else 0)')
if [ "$PY_OK" != "1" ]; then
    echo "✗ 需要 Python 3.9 或更高版本，当前：$("$PYTHON" --version 2>&1)" >&2
    exit 1
fi

mkdir -p "$BIN_DIR"

backup_if_regular_file() {
    # A plain file here is either a previous install or a hand-written script.
    # Either way it must survive, so move a copy outside the repo first.
    local target="$1"
    [ -e "$target" ] || return 0
    [ -L "$target" ] && return 0
    local stamp backup_dir
    stamp="$(date +%Y%m%d-%H%M%S)"
    backup_dir="$BACKUP_ROOT/$stamp"
    mkdir -p "$backup_dir"
    chmod 700 "$BACKUP_ROOT" "$backup_dir"
    cp -p "$target" "$backup_dir/"
    chmod 600 "$backup_dir/$(basename "$target")"
    echo "  已备份 $(basename "$target") → $backup_dir/"
}

# --- install the cskit launcher -------------------------------------------

TARGET="$BIN_DIR/cskit"
if [ -e "$TARGET" ] && [ "$FORCE" -ne 1 ]; then
    echo "✗ 已存在：$TARGET（用 --force 覆盖）" >&2
    exit 1
fi
backup_if_regular_file "$TARGET"

# The launcher points at this checkout, so `git pull` upgrades cskit with no
# reinstall. PYTHONPATH is prepended so the repo wins over any stale copy.
cat > "$TARGET" <<LAUNCHER
#!/usr/bin/env bash
# Generated by cskit install.sh — runs the package from its repo checkout.
export PYTHONPATH="$REPO_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$PYTHON" -m cskit "\$@"
LAUNCHER
chmod 755 "$TARGET"

echo "✓ 已安装：$TARGET"

# --- optional legacy shims ------------------------------------------------

if [ "$WITH_SHIMS" -eq 1 ]; then
    for name in "${LEGACY_NAMES[@]}"; do
        sub="${name%code}"          # fixcode -> fix, exportcode -> export
        shim="$BIN_DIR/$name"
        backup_if_regular_file "$shim"
        cat > "$shim" <<SHIM
#!/usr/bin/env bash
# Generated by cskit install.sh — compatibility shim for '$name'.
exec "$TARGET" $sub "\$@"
SHIM
        chmod 755 "$shim"
        echo "✓ 已创建兼容命令：$shim → cskit $sub"
    done
else
    echo "ℹ 未创建 fixcode/exportcode/clonecode 兼容命令（需要时加 --with-shims）"
    echo "  现有脚本保持不动，可继续作为回滚路径使用。"
fi

# --- PATH hint ------------------------------------------------------------

case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "⚠ $BIN_DIR 不在 PATH 中，请加入后重开终端。" ;;
esac

echo
echo "验证：cskit --version && cskit export --list"
